- hosts: 192.168.29.55
  tasks:
  - name: Adding Docker Repository 
    yum_repository:
           description: Docker Setup
           name: Docker
           baseurl:  https://download.docker.com/linux/centos/7/x86_64/stable
           gpgcheck: no
    register: x

  - debug:
           var : x

  - name: Install Docker Package
    package:
           name: "docker-ce-18.09.1-3.el7.x86_64"
           state: present
    register: y

  - debug: 
          var: y


  - name: Starting docker service
    service:
           name: "docker"
           state: started
           enabled: yes

  - command: yum install python3 -y
  - command: pip3 install docker 

  - name: create local folder 
    file: 
      path: "/ansiblewebserver"
      state: directory 

  - name: coping file 
    copy: 
     src: "/ansiblecode"
     dest: "/ansiblewebserver"
  
  

  

  - name: "Create Docker Container"
    docker_container: 
          name: "ansiblehttpd"
          image: "httpd"
          state: started
          exposed_ports: 
          - "80"
          ports: "8885:80"
          volumes: 
          - /ansiblewebserver:/usr/local/apache2/htdocs
 
    
  
   
  

